apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: anki-config
  namespace: anki
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  # storageClassName: standard   # set to your cluster's class if not default
